
CREATE DATABASE db_ParqueoPrivadosGT;

CREATE TABLE Tbl_Sedes
(
    CodigoSede              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NombreSede              VARCHAR(100) NOT NULL,
    Direccion               VARCHAR(200) NOT NULL,
    Municipio               VARCHAR(100) NOT NULL,
    Departamento            VARCHAR(100) NOT NULL,
    Telefono                VARCHAR(20) NOT NULL,
    HoraApertura            TIME NOT NULL,
    HoraCierre              TIME NOT NULL,
    CapacidadTotal          INT NOT NULL,
    Estado                  VARCHAR(20) NOT NULL
);

CREATE TABLE Tbl_TiposVehiculos
(
    CodigoTipoVehiculo      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NombreTipoVehiculo      VARCHAR(60) NOT NULL,
    Descripcion             VARCHAR(250) NULL,
    FactorTarifa            DECIMAL(5,2) NOT NULL,
    RequiereEspacioAmplio   BOOLEAN NOT NULL,
    Estado                  VARCHAR(20) NOT NULL
);

CREATE TABLE Tbl_Clientes
(
    CodigoCliente           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TipoCliente             VARCHAR(30) NOT NULL,
    NombreCliente           VARCHAR(150) NOT NULL,
    NIT                     VARCHAR(20) NULL,
    DPI                     VARCHAR(20) NULL,
    Telefono                VARCHAR(20) NOT NULL,
    CorreoElectronico       VARCHAR(120) NULL,
    Direccion               VARCHAR(200) NOT NULL,
    FechaRegistro           DATE NOT NULL,
    Estado                  VARCHAR(20) NOT NULL
);

CREATE TABLE Tbl_Vehiculos
(
    CodigoVehiculo          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoCliente           INT NOT NULL,
    CodigoTipoVehiculo      INT NOT NULL,
    Placa                   VARCHAR(20) NOT NULL,
    Marca                   VARCHAR(60) NOT NULL,
    Modelo                  VARCHAR(60) NOT NULL,
    Color                   VARCHAR(30) NOT NULL,
    AnioFabricacion         INT NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Vehiculos_Clientes FOREIGN KEY (CodigoCliente) REFERENCES Tbl_Clientes (CodigoCliente),
    CONSTRAINT FK_Vehiculos_TiposVehiculos FOREIGN KEY (CodigoTipoVehiculo) REFERENCES Tbl_TiposVehiculos (CodigoTipoVehiculo)
);

CREATE TABLE Tbl_Tarifas
(
    CodigoTarifa            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoSede              INT NOT NULL,
    CodigoTipoVehiculo      INT NOT NULL,
    NombreTarifa            VARCHAR(100) NOT NULL,
    PrecioHora              DECIMAL(10,2) NOT NULL,
    PrecioDia               DECIMAL(10,2) NOT NULL,
    PrecioMensual           DECIMAL(10,2) NULL,
    FechaVigenciaInicio     DATE NOT NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Tarifas_Sedes FOREIGN KEY (CodigoSede) REFERENCES Tbl_Sedes (CodigoSede),
    CONSTRAINT FK_Tarifas_TiposVehiculos FOREIGN KEY (CodigoTipoVehiculo) REFERENCES Tbl_TiposVehiculos (CodigoTipoVehiculo)
);

CREATE TABLE Tbl_Espacios
(
    CodigoEspacio           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoSede              INT NOT NULL,
    CodigoTipoVehiculo      INT NOT NULL,
    NumeroEspacio           VARCHAR(20) NOT NULL,
    Nivel                   VARCHAR(30) NULL,
    Zona                    VARCHAR(50) NULL,
    Estado                  VARCHAR(20) NOT NULL,
    Observaciones           VARCHAR(250) NULL,
    CONSTRAINT FK_Espacios_Sedes FOREIGN KEY (CodigoSede) REFERENCES Tbl_Sedes (CodigoSede),
    CONSTRAINT FK_Espacios_TiposVehiculos FOREIGN KEY (CodigoTipoVehiculo) REFERENCES Tbl_TiposVehiculos (CodigoTipoVehiculo)
);

CREATE TABLE Tbl_Empleados
(
    CodigoEmpleado          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoSede              INT NOT NULL,
    Nombres                 VARCHAR(100) NOT NULL,
    Apellidos               VARCHAR(100) NOT NULL,
    DPI                     VARCHAR(20) NOT NULL,
    Puesto                  VARCHAR(60) NOT NULL,
    Telefono                VARCHAR(20) NOT NULL,
    CorreoElectronico       VARCHAR(120) NULL,
    FechaContratacion       DATE NOT NULL,
    NombreUsuario           VARCHAR(80) NOT NULL,
    ClaveAcceso             VARCHAR(255) NOT NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Empleados_Sedes FOREIGN KEY (CodigoSede) REFERENCES Tbl_Sedes (CodigoSede)
);

CREATE TABLE Tbl_Turnos
(
    CodigoTurno             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoEmpleado          INT NOT NULL,
    CodigoSede              INT NOT NULL,
    FechaTurno              DATE NOT NULL,
    HoraInicio              TIME NOT NULL,
    HoraFin                 TIME NOT NULL,
    TipoTurno               VARCHAR(30) NOT NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Turnos_Empleados FOREIGN KEY (CodigoEmpleado) REFERENCES Tbl_Empleados (CodigoEmpleado),
    CONSTRAINT FK_Turnos_Sedes FOREIGN KEY (CodigoSede) REFERENCES Tbl_Sedes (CodigoSede)
);

CREATE TABLE Tbl_Reservaciones
(
    CodigoReservacion       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoCliente           INT NOT NULL,
    CodigoVehiculo          INT NOT NULL,
    CodigoSede              INT NOT NULL,
    CodigoEspacio           INT NOT NULL,
    FechaHoraReservacion    TIMESTAMP NOT NULL,
    FechaHoraInicio         TIMESTAMP NOT NULL,
    FechaHoraFin            TIMESTAMP NOT NULL,
    Observaciones           VARCHAR(250) NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Reservaciones_Clientes FOREIGN KEY (CodigoCliente) REFERENCES Tbl_Clientes (CodigoCliente),
    CONSTRAINT FK_Reservaciones_Vehiculos FOREIGN KEY (CodigoVehiculo) REFERENCES Tbl_Vehiculos (CodigoVehiculo),
    CONSTRAINT FK_Reservaciones_Sedes FOREIGN KEY (CodigoSede) REFERENCES Tbl_Sedes (CodigoSede),
    CONSTRAINT FK_Reservaciones_Espacios FOREIGN KEY (CodigoEspacio) REFERENCES Tbl_Espacios (CodigoEspacio)
);

CREATE TABLE Tbl_Entradas
(
    CodigoEntrada           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoVehiculo          INT NOT NULL,
    CodigoEspacio           INT NOT NULL,
    CodigoEmpleado          INT NOT NULL,
    CodigoReservacion       INT NULL,
    FechaHoraEntrada        TIMESTAMP NOT NULL,
    Observaciones           VARCHAR(250) NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Entradas_Vehiculos FOREIGN KEY (CodigoVehiculo) REFERENCES Tbl_Vehiculos (CodigoVehiculo),
    CONSTRAINT FK_Entradas_Espacios FOREIGN KEY (CodigoEspacio) REFERENCES Tbl_Espacios (CodigoEspacio),
    CONSTRAINT FK_Entradas_Empleados FOREIGN KEY (CodigoEmpleado) REFERENCES Tbl_Empleados (CodigoEmpleado),
    CONSTRAINT FK_Entradas_Reservaciones FOREIGN KEY (CodigoReservacion) REFERENCES Tbl_Reservaciones (CodigoReservacion)
);

CREATE TABLE Tbl_Salidas
(
    CodigoSalida            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoEntrada           INT NOT NULL,
    CodigoEmpleado          INT NOT NULL,
    FechaHoraSalida         TIMESTAMP NOT NULL,
    TiempoTotalMinutos      INT NOT NULL,
    Observaciones           VARCHAR(250) NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Salidas_Entradas FOREIGN KEY (CodigoEntrada) REFERENCES Tbl_Entradas (CodigoEntrada),
    CONSTRAINT FK_Salidas_Empleados FOREIGN KEY (CodigoEmpleado) REFERENCES Tbl_Empleados (CodigoEmpleado)
);

CREATE TABLE Tbl_Pagos
(
    CodigoPago              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoSalida            INT NOT NULL,
    CodigoTarifa            INT NOT NULL,
    CodigoCliente           INT NOT NULL,
    MontoPago               DECIMAL(10,2) NOT NULL,
    FormaPago               VARCHAR(50) NOT NULL,
    ReferenciaPago          VARCHAR(100) NULL,
    FechaHoraPago           TIMESTAMP NOT NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Pagos_Salidas FOREIGN KEY (CodigoSalida) REFERENCES Tbl_Salidas (CodigoSalida),
    CONSTRAINT FK_Pagos_Tarifas FOREIGN KEY (CodigoTarifa) REFERENCES Tbl_Tarifas (CodigoTarifa),
    CONSTRAINT FK_Pagos_Clientes FOREIGN KEY (CodigoCliente) REFERENCES Tbl_Clientes (CodigoCliente)
);

CREATE TABLE Tbl_Incidencias
(
    CodigoIncidencia        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoSede              INT NOT NULL,
    CodigoEmpleado          INT NOT NULL,
    CodigoVehiculo          INT NULL,
    CodigoEspacio           INT NULL,
    TipoIncidencia          VARCHAR(60) NOT NULL,
    Descripcion             VARCHAR(500) NOT NULL,
    FechaHoraIncidencia     TIMESTAMP NOT NULL,
    Estado                  VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Incidencias_Sedes FOREIGN KEY (CodigoSede) REFERENCES Tbl_Sedes (CodigoSede),
    CONSTRAINT FK_Incidencias_Empleados FOREIGN KEY (CodigoEmpleado) REFERENCES Tbl_Empleados (CodigoEmpleado),
    CONSTRAINT FK_Incidencias_Vehiculos FOREIGN KEY (CodigoVehiculo) REFERENCES Tbl_Vehiculos (CodigoVehiculo),
    CONSTRAINT FK_Incidencias_Espacios FOREIGN KEY (CodigoEspacio) REFERENCES Tbl_Espacios (CodigoEspacio)
);
